---
title: "304 fianl"
output: html_document
---



```{r}


library(tidyverse)
library(haven)
```

```{r}

library(NHANES)
library(tidyverse)



small.nhanes <- na.omit(NHANES[NHANES$SurveyYr=="2011_12"
                               & NHANES$Age > 17,c(1,3,4,8:11,13,17,20,21,25,46,50,51,52,61)])
small.nhanes <- as.data.frame(small.nhanes %>%
  group_by(ID) %>% filter(row_number()==1) )
nrow(small.nhanes)

```

```{r}
summary(small.nhanes)
```


```{r}

small.nhanes<-small.nhanes %>% 
                      mutate(age_group = case_when(
                                             Age >20  & Age <= 30 ~ '21 to 30',
                                             Age >30  & Age <= 40 ~ '31 to 40',
                                             Age >40  & Age <= 50 ~ '41 to 50',
                                             Age >50  & Age <= 60 ~ '51 to 60',
                                             Age >60  & Age <= 70 ~ '61 to 70',
                                             Age >70 ~ 'above 70'))






```


```{r}
small.nhanes$BPSysAve <- ifelse(small.nhanes$BPSysAve>=130, 1,0)
```


```{r}
small.nhanes<-small.nhanes %>% 
                      mutate(weight = case_when(
                                             Weight <= 50 ~ 'Less than 50',
                                             Weight >50  & Weight <= 60 ~ '50 to 60',
                                             Weight >60  & Weight <= 70 ~ '60 to 70',
                                             Weight >70  & Weight <= 80 ~ '70 to 80',
                                             Weight >80  & Weight <= 100 ~ '80 to 100',
                                             Weight >100 ~ 'above 100'))


```


```{r}
small.nhanes<-small.nhanes %>% 
                      mutate(poverty = case_when(
                                             Poverty <= 1 ~ 'Poverty_level1',
                                             Poverty >1  & Poverty <= 2 ~ 'Poverty_level2',
                                             Poverty >2  & Poverty <= 3 ~ 'Poverty_level2',
                                             Poverty >3  & Poverty <= 4 ~ 'Poverty_level3',
                                             Poverty >4  & Poverty < 5 ~ 'Poverty_level4',
                                             Poverty >=5 ~ 'Poverty_level5'))


```


```{r}

model.lm <- lm( BPSysAve ~ ., data = small.nhanes[, -c(1)], y = small.nhanes$BPSysAve,family= 'binomial')
summary(model.lm)

```



```{r}

model <- lm( BPSysAve ~ age_group + Gender+weight+poverty , data = small.nhanes[, -c(1)], y = small.nhanes$BPSysAve,family= 'binomial')
summary(model)
```



```{r}
library(tidyverse)
library(haven)
```





```{r}
reduced_data <- 
  usa_00002 %>% 
  select( SEX, AGE, INCTOT, HHWT)
```

```{r}
reduced_data <- reduced_data[(21<=reduced_data$AGE),]
reduced_data<-reduced_data %>% 
                      mutate(Gender = case_when( SEX==1 ~ 'male',
                                                 SEX==2 ~ 'female'))
```


```{r}
reduced_data<-reduced_data %>% 
                      mutate(age_group = case_when(
                                             AGE >20  & AGE <= 30 ~ '21 to 30',
                                             AGE >30  & AGE <= 40 ~ '31 to 40',
                                             AGE >40  & AGE <= 50 ~ '41 to 50',
                                             AGE >50  & AGE <= 60 ~ '51 to 60',
                                             AGE >60  & AGE <= 70 ~ '61 to 70',
                                             AGE >70 ~ 'above 70'))

```


```{r}
reduced_data<-reduced_data %>% 
                      mutate(weight = case_when(
                                             HHWT <= 50 ~ 'Less than 50',
                                             HHWT >50  & HHWT <= 60 ~ '50 to 60',
                                             HHWT >60  & HHWT <= 70 ~ '60 to 70',
                                             HHWT >70  & HHWT <= 80 ~ '70 to 80',
                                             HHWT >80  & HHWT <= 100 ~ '80 to 100',
                                             HHWT >100 ~ 'above 100'))


```


```{r}
reduced_data<-reduced_data %>% 
                      mutate(Poverty = INCTOT/20000)
```

```{r}
reduced_data<-reduced_data %>% 
                      mutate(poverty = case_when(
                                             Poverty <= 1 ~ 'Poverty_level1',
                                             Poverty >1  & Poverty <= 2 ~ 'Poverty_level2',
                                             Poverty >2  & Poverty <= 3 ~ 'Poverty_level2',
                                             Poverty >3  & Poverty <= 4 ~ 'Poverty_level3',
                                             Poverty >4  & Poverty < 5 ~ 'Poverty_level4',
                                             Poverty >=5 ~ 'Poverty_level5'))


```

```{r}
census_data <- 
  reduced_data %>%
  count(age_group, poverty, weight, Gender) %>%
  group_by(age_group, poverty, weight, Gender) 

```


```{r}
census_data$logodds_estimate <-
  model %>%
  predict(newdata = census_data)

census_data$estimate <-
  exp(census_data$logodds_estimate)/(1+exp(census_data$logodds_estimate))

census_data %>%
  mutate(alp_predict_prop = estimate*n) %>%
  summarise(alp_predict = sum(alp_predict_prop)/sum(n))


```




