---
title: "304 final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(NHANES)
library(tidyverse)
library(glmnet)


small.nhanes <- na.omit(NHANES[NHANES$SurveyYr=="2011_12"
                               & NHANES$Age > 17,c(1,3,4,8:11,13,17,20,21,25,46,50,51,52,61)])
small.nhanes <- as.data.frame(small.nhanes %>%
  group_by(ID) %>% filter(row_number()==1) )
nrow(small.nhanes)

```
```{r}
length(unique(small.nhanes$ID))

```
```{r}
small.nhanes$BPSysAve <- ifelse(small.nhanes$BPSysAve>=130,1,0)
small.nhanes<-small.nhanes %>% 
                      mutate(age_group = case_when(
                                             Age >20  & Age <= 30 ~ '21 to 30',
                                             Age >30  & Age <= 40 ~ '31 to 40',
                                             Age >40  & Age <= 50 ~ '41 to 50',
                                             Age >50  & Age <= 60 ~ '51 to 60',
                                             Age >60  & Age <= 70 ~ '61 to 70',
                                             Age >70 ~ 'above 70'))
```


```{r}

model.lm <- lm( BPSysAve ~ ., data = small.nhanes[, -c(1)], y = small.nhanes$BPSysAve,family= 'binomial')
summary(model.lm)

```

```{r}
library(olsrr)
library(tidyverse)
library(haven)
```



```{r}
ols_step_forward_p(model.lm)
```


```{r}
model.lm2 <- lm( BPSysAve ~ age_group + Gender+ Poverty+Weight+HHIncome , data = small.nhanes[, -c(1)], y = small.nhanes$BPSysAve,family= 'binomial')
summary(model.lm2)

```
